language: python
branches:
  only:
    - master
python: 3.7
dist: xenial
sudo: true
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=imagesearch/
after_success:
  - coveralls
