swagger: '2.0'
info:
  description: 'This page lists all the REST APIs for the Image Search App.'
  version: '1.0.0'
  title: 'Image Search App'
  contact:
    email: 'mikelowedev@gmail.com'
  license:
    name: 'MIT'
    url: 'https://github.com/vanillaSlice/ImageSearch/blob/master/LICENSE'

basePath: '/'

paths:
  /search/{terms}:
    get:
      operationId: 'imagesearch.blueprints.search'
      tags:
        - 'Image Search'
      summary: 'Performs search'
      description: 'Returns image search results'
      parameters:
        - name: 'terms'
          in: 'path'
          description: 'Search terms'
          required: true
          type: 'string'
      responses:
        200:
          description: 'Returns image search results'  
  /latest:
    get:
      operationId: 'imagesearch.blueprints.latest'
      tags:
        - 'Image Search'
      summary: 'Latest searches'
      description: 'Returns the latest searches'
      responses:
        200:
          description: 'Returns the latest searches'
